### ISSUE TITLE
Show smaller UI when few items are returned

### ISSUE THREAD

**Issue by Gegy** [Gegy/whats-that-slot#4]
Currently, we always show the 5x5 item slots, even when only a few search results are returned. This can be quite intrusive and awkward. Ideally we would be able to select a smaller texture depending on how many results are displayed.

**Comment by mezz** [comment]
JEI's NineSlice drawing thingy code may be pretty good for this purpose, you can use the one existing texture and resize it in code:
https://github.com/mezz/JustEnoughItems/blob/7571d601d8d74170d7384952b07e564d0f7c11a3/src/main/java/mezz/jei/gui/elements/DrawableNineSliceTexture.java#L17-L21
