### ISSUE TITLE
1.19.2 not really supported

### ISSUE THREAD

**Issue by passthesh3ll** [Gegy/whats-that-slot#9]
Hello, curseforge shows this mod is compatible with 1.19.2
![image](https://user-images.githubusercontent.com/63223659/184850268-c3e7bfeb-0c1f-4be1-92cb-acf22b620c29.png)
but it seems to be not compatible
![image](https://user-images.githubusercontent.com/63223659/184850758-ed3db624-0da1-4e12-a195-6002d9b7ce7d.png)

What is the latest minecraft version supported?

**Comment by Gegy** [comment]
Oops! Thanks for the heads up- the version requirement for the Fabric version is a bit more restrictive than the Forge version. Will push a release out soon!

**Comment by Gegy** [comment]
Pushed 1.3.1 to resolve this issue 🙂
